In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [3]:
dt=pd.read_csv(r"Documents\Python Scripts\DataSet\voice.csv")
dt.head(10)

,meanfreq,sd,median,Q25,Q75,IQR,skew,kurt,sp.ent,sfm,...,centroid,meanfun,minfun,maxfun,meandom,mindom,maxdom,dfrange,modindx,label
0,0.059781,0.064241,0.032027,0.015071,0.090193,0.075122,12.863462,274.402906,0.893369,0.491918,...,0.059781,0.084279,0.015702,0.275862,0.007812,0.007812,0.007812,0.000000,0.000000,male
1,0.066009,0.067310,0.040229,0.019414,0.092666,0.073252,22.423285,634.613855,0.892193,0.513724,...,0.066009,0.107937,0.015826,0.250000,0.009014,0.007812,0.054688,0.046875,0.052632,male
2,0.077316,0.083829,0.036718,0.008701,0.131908,0.123207,30.757155,1024.927705,0.846389,0.478905,...,0.077316,0.098706,0.015656,0.271186,0.007990,0.007812,0.015625,0.007812,0.046512,male
3,0.151228,0.072111,0.158011,0.096582,0.207955,0.111374,1.232831,4.177296,0.963322,0.727232,...,0.151228,0.088965,0.017798,0.250000,0.201497,0.007812,0.562500,0.554688,0.247119,male
4,0.135120,0.079146,0.124656,0.078720,0.206045,0.127325,1.101174,4.333713,0.971955,0.783568,...,0.135120,0.106398,0.016931,0.266667,0.712812,0.007812,5.484375,5.476562,0.208274,male
5,0.132786,0.079557,0.119090,0.067958,0.209592,0.141634,1.932562,8.308895,0.963181,0.738307,...,0.132786,0.110132,0.017112,0.253968,0.298222,0.007812,2.726562,2.718750,0.125160,male
6,0.150762,0.074463,0.160106,0.092899,0.205718,0.112819,1.530643,5.987498,0.967573,0.762638,...,0.150762,0.105945,0.026230,0.266667,0.479620,0.007812,5.312500,5.304688,0.123992,male
7,0.160514,0.076767,0.144337,0.110532,0.231962,0.121430,1.397156,4.766611,0.959255,0.719858,...,0.160514,0.093052,0.017758,0.144144,0.301339,0.007812,0.539062,0.531250,0.283937,male
8,0.142239,0.078018,0.138587,0.088206,0.208587,0.120381,1.099746,4.070284,0.970723,0.770992,...,0.142239,0.096729,0.017957,0.250000,0.336476,0.007812,2.164062,2.156250,0.148272,male
9,0.134329,0.080350,0.121451,0.075580,0.201957,0.126377,1.190368,4.787310,0.975246,0.804505,...,0.134329,0.105881,0.019300,0.262295,0.340365,0.015625,4.695312,4.679688,0.089920,male

In [4]:
dt.label = [1 if each == "male" else 0 for each in dt.label]

In [5]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3168 entries, 0 to 3167
Data columns (total 21 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   meanfreq  3168 non-null   float64
 1   sd        3168 non-null   float64
 2   median    3168 non-null   float64
 3   Q25       3168 non-null   float64
 4   Q75       3168 non-null   float64
 5   IQR       3168 non-null   float64
 6   skew      3168 non-null   float64
 7   kurt      3168 non-null   float64
 8   sp.ent    3168 non-null   float64
 9   sfm       3168 non-null   float64
 10  mode      3168 non-null   float64
 11  centroid  3168 non-null   float64
 12  meanfun   3168 non-null   float64
 13  minfun    3168 non-null   float64
 14  maxfun    3168 non-null   float64
 15  meandom   3168 non-null   float64
 16  mindom    3168 non-null   float64
 17  maxdom    3168 non-null   float64
 18  dfrange   3168 non-null   float64
 19  modindx   3168 non-null   float64
 20  label     3168 non-null   int64
dtypes: float64(20), int64(1)
memory usage: 519.9 KB

In [8]:
Y = dt.label.values
X_dt = dt.drop(["label"], axis = 1)

In [9]:
X = (X_dt - np.min(X_dt))/(np.max(X_dt)-np.min(X_dt)).values

In [18]:
train,test=train_test_split(dt,test_size=0.2)

In [19]:
print(train.shape)
print(test.shape)

(2534, 21)
(634, 21)

In [20]:
Prediction_var=['meanfreq','sd','median','Q25','Q75','IQR','skew','kurt','sp.ent','centroid','dfrange']
Prediction_var

['meanfreq',
 'sd',
 'median',
 'Q25',
 'Q75',
 'IQR',
 'skew',
 'kurt',
 'sp.ent',
 'centroid',
 'dfrange']

In [21]:
X_train=train[Prediction_var]
Y_train=train['label']

In [22]:
X_test=test[Prediction_var]
Y_test=test['label']

In [23]:
logistic_model=LogisticRegression()
logistic_model.fit(X_train,Y_train)

C:\Users\MINE\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [25]:
Predicted_value=logistic_model.predict(X_test)

In [26]:
metrics.accuracy_score(Y_test,Predicted_value)

0.831230283911672

In [28]:
Y_test

1917    0
1248    1
2076    0
1318    1
1809    0
       ..
2792    0
361     1
1621    0
631     1
232     1
Name: label, Length: 634, dtype: int64

In [29]:
d=pd.DataFrame({'Predicated_value':Predicted_value,'KnownO/P':Y_test})
d.head(50)

      Predicated_value  KnownO/P
1917                 1         0
1248                 1         1
2076                 1         0
1318                 1         1
1809                 0         0
1839                 0         0
832                  1         1
700                  1         1
247                  1         1
1469                 1         1
2058                 1         0
392                  1         1
2146                 0         0
2019                 1         0
2186                 0         0
1001                 1         1
1256                 1         1
1721                 0         0
1720                 0         0
2267                 0         0
1599                 0         0
2823                 0         0
1536                 1         1
577                  1         1
2173                 0         0
401                  1         1
1189                 1         1
2435                 0         0
3046                 0         0
2691                 0         0
1371                 0         1
654                  1         1
1841                 0         0
568                  1         1
1432                 1         1
2531                 0         0
427                  1         1
1128                 1         1
1451                 0         1
599                  0         1
386                  1         1
650                  1         1
2108                 0         0
905                  1         1
2330                 0         0
2740                 0         0
332                  1         1
2845                 0         0
843                  1         1
1524                 1         1